import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComp from "@/components/HeaderComp";
import { CartProvider } from '@/store';
import { FavoritsProvider} from '@/favorits';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html

      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col"> 
        
    <FavoritsProvider>
          <HeaderComp/>
          <CartProvider>
        {children} 
          </CartProvider>

    </FavoritsProvider>
        </body>
      
    
    </html>
  );
}
